name: slack-notify
description: "Install slack-notify."
inputs:
  version:
    description: "A version to install slack-notify."
    default: "v0.0.8"

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        cd /tmp
        curl -sLO https://github.com/ebc-2in2crc/slack-notify/releases/download/${{ inputs.version }}/slack-notify_linux_amd64.zip
        unzip slack-notify_linux_amd64.zip
        sudo install slack-notify_linux_amd64/slack-notify /usr/local/bin
        rm -rf slack-notify_linux_amd64/ slack-notify_linux_amd64.zip
        slack-notify -v